name: Build new release APK

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Get latest release from NetherSX2-patch repository
        run: |
          LATEST_JSON="$(curl -s https://api.github.com/repos/Trixarian/NetherSX2-patch/releases/latest)"
          LATEST_TAG="$(echo "$LATEST_JSON" | jq -r .tag_name)"
          echo "LATEST_TAG=$LATEST_TAG" >> "$GITHUB_ENV"

      - name: Compare with last known release
        run: |
          LAST_TAG=""
          if [ -f .release_version ]; then
            LAST_TAG="$(cat .release_version)"
          fi
          echo "Last known release tag: $LAST_TAG"
          echo "Latest release tag: $LATEST_TAG"
          if [ "$LAST_TAG" = "$LATEST_TAG" ]; then
            echo "IS_NEW=0" >> "$GITHUB_ENV"
          else
            echo "IS_NEW=1" >> "$GITHUB_ENV"
          fi

  build-release:
    runs-on: ubuntu-24.04
    steps:
      - name: build
        run: |
          ls -la

  update-release-file:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Update stored release version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          echo "$LATEST_TAG" > .release_version
          git add .release_version
          git commit -m "Update last release tag to $LATEST_TAG"
          git push